model:
  type: VISION_CLS
  name: resnet18
  params:
    num_classes: 10
    pretrained: False

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.001
  max_epochs: 20
  callbacks:
    ModelCheckpoint:
      params:
        filename: dummy_checkpoint_rsnt18

data:
  dataset_name: CIFAR10
  batch_size: 200
  num_workers: 4


quantization:
  name: dummy
  act_bit: 0
  weight_bit: 0
