model:
  type: VISION_CLS
  name: resnet20_cifar10_new
  params:
    pretrained: True
    num_classes: 10

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.0005
  max_epochs: 1500
  val_every_n_epochs: 2
  log_every_n_steps: 10
  loggers:
    WandbLogger:
      params:
        name: resnet20-rniq
        note: "noise + deepdream features.stage3.unit3.body.conv2.conv, step_size = 0.2, back input for tmodel + grad rework. 0.7 for act loss"
  callbacks:
    ModelCheckpoint:
      params:
        monitor: Metric/ns_Accuracy_top1
        mode: max
        filename: rniq_checkpoint-{epoch:02d}-"{Metric/ns_Accuracy_top1:.2f}"
    ReduceLrOnOutlier:
      params:
        reduce_scale: 4
        lr_lim: 0.001
    RandNoiseScale:
      params:
        reduce_scale: 2

data:
  dataset_name: CIFAR10_NOISE
  batch_size: 3000
  num_workers: 8


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  weight_bit: 4
  act_bit: 4
  distillation: True
  distillation_loss: KL
  excluded_layers:
    - 'features.init_block.conv'
    - 'output'
