model:
  type: VISION_CLS
  name: resnet18
  params:
    num_classes: 10
    weights: null

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.0001
  max_epochs: 400
  val_every_n_epochs: 20
  log_every_n_steps: 10
  callbacks:
    ModelCheckpoint:
      params:
        filename: rniq_checkpoint_rsnt18
    ReduceLrOnOutlier:
      params:
        reduce_scale: 2
    RandNoiseScale:
      params:
        reduce_scale: 2

data:
  dataset_name: CIFAR10
  batch_size: 8192
  num_workers: 20


quantization:
  name: RNIQQuant
  act_bit: 4
  weight_bit: 4
  excluded_layers:
    - 'model.fc'
