model:
  type: VISION_CLS
  name: resnet18
  params:
    pretrained: True
    num_classes: 1000

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.001
  max_epochs: 700
  val_every_n_epochs: 2
  log_every_n_steps: 10
  loggers:
    WandbLogger:
      params:
        name: resnet18-rniq
        note: "Testing MAE loss with soft probs for tinputs and targets with linear noise decrease"
 
  callbacks:
    ModelCheckpoint:
      params:
        filename: rniq_checkpoint_rsnt18
    ReduceLrOnOutlier:
      params:
        reduce_scale: 8
    RandNoiseScale:
      params:
        reduce_scale: 2

data:
  dataset_name: Imagenet
  batch_size: 3800
  num_workers: 10


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  act_bit: 21
  weight_bit: 2
  excluded_layers:
    - 'conv1'
    - 'fc'
