model:
  type: VISION_CLS
  name: resnet20_cifar10
  params:
    pretrained: True
    num_classes: 10

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.001
  max_epochs: 1500
  val_every_n_epochs: 2
  log_every_n_steps: 10
  loggers:
    WandbLogger:
      params:
        name: resnet20-rniq
        note: "proper ckpt, noisy depdream"
 
  callbacks:
    ModelCheckpoint:
      params:
        filename: rniq_checkpoint_rsnt20
    ReduceLrOnOutlier:
      params:
        reduce_scale: 4
        lr_lim: 0.005
    RandNoiseScale:
      params:
        reduce_scale: 2

data:
  dataset_name: CIFAR10_NOISE
  batch_size: 2000
  num_workers: 6


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  act_bit: 2
  weight_bit: 2
  distillation: True
  distillation_loss: Symmetrical KL
  excluded_layers:
    - 'module.linear'
    - 'module.conv1'
